---
title: "About Us"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Ashley Romo

Ashley is a second-year MPH candidate in the Department of Epidemiology at Columbia University Mailman School of Public Health. She is pursuing a certificate in Applied Biostatistics and Public Health Data Science.

[LinkedIn](https://www.linkedin.com/in/ashley-romo-963a35129/)
### Caleigh Dwyer

Caleigh is a second-year MPH candidate in the Department of Sociomedical Sciences at Columbia University Mailman School of Public Health. She is pursuing a certificate in Public Health Research Methods.

### Hsin Yi (Cindy) Tseng

Hsin Yi (Cindy) is a second-year MPH candidate in the Department of Epidemiology at Columbia University Mailman School of Public Health. She is pursuing a certificate in Applied Biostatistics and Public Health Data Science.

### Sarah Younes

Sarah is a second-year MPH candidate in the Department of Sociomedical Sciences at Columbia University Mailman School of Public Health. She is pursuing a certificate in Public Health Research Methods.

[LinkedIn](https://www.linkedin.com/in/sarahmyounes/)

### Wen Dai

Wen is a second-year MPH candidate in the Department of Epidemiology at Columbia University Mailman School of Public Health. She is pursuing a certificate in Applied Biostatistics and Public Health Data Science.