---
title: "Introduction"
output: 
  html_document:
    toc: true
    toc_float: true
---

Welcome to our final project for our Data Science I course! Our project explores trends in mental health access in the United States since the COVID-19 pandemic, as well as differences in mental health access by various demographic characteristics. We used existing data from the Household Pulse Survey, which is a nationally representative quantitative survey. Our data cleaning and analysis were conducted in RStudio.

We value transparency and reproducibility; as such, our R code is linked in our GitHub repository, which can be found by clicking [this link](https://github.com/romoashley/p8105_final_mental_health) or by clicking the icon on the top right navigation menu.

Please see the screencast below for an introduction to our project and guide to our website.

## Collaborators

* Ashley Romo (ar4459)
* Caleigh Dwyer (crd2162)
* Hsin Yi (Cindy) Tseng (ht2607)
* Sarah Younes (smy2122)
* Wen Dai (wz2629)