---
title: "Linear Modeling"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: "hide"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message = FALSE, echo = FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
library(MASS) # for stepAIC
library(dplyr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Step 1 
Import the tidy dataset
```{r}
library(tidyverse)

tidydata = 
  read.csv("data/tidydata.csv")
```

## Step 2 
Separate tidy dataset into 4 subgroups based on the indicator category.
```{r}
Indicator1=tidydata |> filter(indicator=="Took Prescription Medication for Mental Health")
Indicator2=tidydata |> filter(indicator=="Received Counseling or Therapy")
Indicator3=tidydata |> filter(indicator=="Took Prescription Medication for Mental Health And/Or Received Counseling or Therapy")
Indicator4=tidydata |> filter(indicator=="Needed Counseling or Therapy But Did Not Get It")
```

## Step 3 
Apply linear model
```{r}

fit <- lm(value ~ group + subgroup + year + state, data=Indicator1)
stepwise_fit <- stepAIC(fit, direction="both")

fit <- lm(value ~ group + subgroup + year + state, data=Indicator2)
stepwise_fit <- stepAIC(fit, direction="both")

fit <- lm(value ~ group + subgroup + year + state, data=Indicator3)
stepwise_fit <- stepAIC(fit, direction="both")

fit <- lm(value ~ group + subgroup + year + state, data=Indicator4)
stepwise_fit <- stepAIC(fit, direction="both")

```

## Step 4 
AIC values are identical across the steps shown, which suggests that removal or addition of a variable did not improve the model's fit. 





