---
title: "Final Report"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: "hide"
---

## Motivation

COVID-19 has had serious behavioral and mental health implications. One survey conducted by the Centers for Disease Control and Prevention in July 2020 found that [41%](https://www.cnn.com/2020/08/13/health/mental-health-coronavirus-pandemic-cdc-study-wellness/index.html) of respondents were struggling with mental health issues stemming from the pandemic. Different demographics have worse outcomes, such as [young people](https://www.pewresearch.org/short-reads/2023/03/02/mental-health-and-the-pandemic-what-u-s-surveys-have-found/), and these outcomes are [continuing](https://www.kff.org/mental-health/issue-brief/the-implications-of-covid-19-for-mental-health-and-substance-use/) years after the pandemic first hit.

Our project aimed to explore trends and differences in indicators of mental health care access across the United States from August 2020-May 2022, as well as disaggregate data by state, age group, gender, race/ethnicity, education level, and sexual orientation.

## Related Work

Many of us remember reading articles about the difficulty of accessing therapists and counselors during the rise of the COVID-19 pandemic in spring 2020. Providers reported month-long waiting lists that they have [never seen](https://www.cnn.com/2020/12/18/health/mental-health-care-demand-wellness/index.html) until the pandemic hit in spring 2020.

Yet these trends did not taper off; instead, they continued to worsen. According to the [American Psychological Association](https://www.apa.org/news/press/releases/2021/10/mental-health-treatment-demand), the percent of psychologists who treat anxiety and depression who saw an increase in demand for anxiety or depression treatment increased by 13.5% and 20%, respectively, from 2020 to 2021. The number of psychologists who reported receiving more referrals increased from 37% in 2020 to 62% in 2021. Nearly 7 in 10 psychologists with a waiting list in 2021 reported it had grown longer since the start of the pandemic. Even through March 2022, prospective patients are [still](https://www.washingtonpost.com/health/2022/03/06/therapist-covid-burnout/) struggling to find providers who are accepting new patients or do not have month-long waiting lists.

## Data

We are using the [Mental Health Care in the Last 4 Weeks](https://catalog.data.gov/dataset/mental-health-care-in-the-last-4-weeks) data set. Data was collected as part of the Pulse Household Survey across the United States with the U.S. Census Bureau and numerous other federal agencies. The mental health portion of the survey asks respondents to look back in the last 4 weeks and answer whether they:

* Received counseling or therapy for mental health,
* Took prescription medication for mental health, and
* Needed counseling or therapy but did not get it.

The data set includes an additional indicator that combines those who received counseling or therapy and/or took prescription medication for mental health. The percentage of participants who responded "Yes" were calculated for each of the 3 questions they were asked, as well as the additional indicator. It is  possible that participants respond "No" to each of the 3 questions they are asked, so the values for the 3 questions do not add up to 100%.

Data was collected from a nationally representative sample of approximately [50,000-90,000](https://www.cdc.gov/nchs/covid19/pulse/mental-health-care.htm) participants every two weeks for a total of 38 time periods of data collection.

### Data Cleaning

The data set is available for download in multiple formats on  [catalog.data.gov](https://catalog.data.gov/dataset/mental-health-care-in-the-last-4-weeks), and we downloaded the Comma Separated Values (.csv) file.

The first portion of data cleaning was the data import, which involved downloading and importing the .csv using `read_csv` and saving the raw data set.

The second portion of data cleaning was renaming and cleaning columns. This step involved removing unnecessary columns, cleaning and renaming columns for clarity, and dropping missing values.

The third portion of data cleaning was tidying the date formats. This step involved converting dates to the date format using `mdy`, creating a new numeric `year` variable, and cleaning the week numbers and labels.

```{r message = FALSE}
## part 1: importing raw data

library(tidyverse)

rawdata =
  read_csv("data/mental_health.csv")

## part 2: renaming and cleaning columns

tidydata = 
  rawdata |> 
  janitor::clean_names() |>
  dplyr::select(-phase, -quartile_range, -suppression_flag) |>
  dplyr::mutate(
    indicator = str_replace(indicator, ", Last 4 Weeks", ""),
    group = str_replace(group, "By ", "")) |>
  drop_na(value) |>
  dplyr::select(start_date = time_period_start_date, end_date = time_period_end_date, everything())

## part 3: tidying dates

tidydata =
  tidydata |>
  dplyr::mutate(
    week_number = match(time_period_label, unique(time_period_label)),
    start_dates = mdy(pull(tidydata, start_date)),
    end_dates = mdy(pull(tidydata, end_date)),
    tpl = time_period_label,
    year = as.numeric(str_extract(tpl, "\\d{4}"))) |>
  separate(col = time_period_label, into = c("week_label", "years"), sep = ", ", remove = FALSE, extra = "merge") |>
  dplyr::select(indicator, year, start_dates, end_dates, week_number, week_label = time_period_label, state, group, subgroup, value, low_ci, high_ci, confidence_interval)
```

### Final Data Set

The final tidy data set included 13 variables:

* `indicator` (chr): The type of mental health care.
* `year` (num): The year of the time period for data collection.
    * If the time period for data collection continued onto the following year, the year that data collection began was used for this variable.
* `start_dates` (date): The start date of the time period for data collection.
* `end_dates` (date): The end date of the time period for data collection.
* `week_number` (num): The week number of data collection.
    * It should be noted that the data set refers to "weeks" as the two-week data collection period, so each week number indicates a two-week period.
* `week_label` (chr): The dates for the corresponding week.
* `state` (chr): The state or national level data.
* `group` (chr): The demographic group.
* `subgroup` (chr): The specific subgroup within the group.
* `value` (num): The value (percentage or number) representing the indicator.
* `low_ci` (num): Lower bound of the confidence interval of the value.
* `high_ci` (num): Upper bound of the confidence interval of the value.
* `confidence_interval` (chr): Confidence interval as a range.

## Initial Questions

We are interested in identifying trends over time at the national, state, and demographic level. Our initial questions were the following:

* What is the national prevalence over time ? 
* Are there are the differences among states ? Which states have the highest values and which states have the lowest values?
* Are there difference by gender, sexuality, race/ethnicity, age, and education?
* What is the proportion of services needed but not received by individuals in New York? across states?
* What is the proportion of services needed but not received by individuals across states?
* Can we apply a linear model to the data?
* Is there a significant difference between gender and indicators?
* Is there a signficant differences between sexual orientation and indiators?

## Exploratory Analysis

We conducted Exploratory Data Analysis (EDA) at the [national-level](EDA_AR.html), [state-level](eda.html), and [demographic-level](eda_demographic.html).

## Additional Analysis

We conducted a [Two Sample T Test and ANOVA](statistical_analysis.html) to determine if there were difference across indicator categories.

## Results and Discussion

### National Level
On average, those who took prescription medication for mental health and/or received counseling or therapy had a highest values while those who received counseling or therapy had the lowest value. There is a wide gap in average values between those who took prescription medication for mental health and those who needed counseling or therapy but did not get it. Overall, each indicator had a small increase in average value between 2020 and 2022. Additionally, the majority of states had a similar estimate of proportion of mental health services not received within each state. However, Vermont, Wyoming, Hawaii, and North Dakota had distinct estimates, with a lower estimate compared to the remaining states. Overall, Vermont had the lowest estimate. 



