<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Statistical Analysis</title>

<script src="site_libs/header-attrs-2.24/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Exploratory Analyses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="EDA_AR.html">National-Level</a>
    </li>
    <li>
      <a href="eda.html">State-Level</a>
    </li>
    <li>
      <a href="eda_demographic.html">Demographic-Level</a>
    </li>
  </ul>
</li>
<li>
  <a href="statistical_analysis.html">Statistical Analysis</a>
</li>
<li>
  <a href="report.html">Final Report</a>
</li>
<li>
  <a href="about.html">About Us</a>
</li>
<li>
  <a href="https://github.com/romoashley/p8105_final_mental_health">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Statistical Analysis</h1>

</div>


<div id="independent-samples-t-tests" class="section level2">
<h2>Independent Samples T-tests</h2>
<p>We will first conduct independent samples t-tests to see if there is
a statistical relationship between gender and two of our indicators of
mental health access:</p>
<ol style="list-style-type: decimal">
<li>Took prescription medication and/or received counseling or therapy
for mental health</li>
<li>Needed counseling or therapy for mental health but did not get
it</li>
</ol>
<p>Even though the independent samples t-test assumes normality, our
sample size (50,000-90,000) is large. The Central Limit Theorem often
allows the t-test to be used even when the population distribution is
not normal, because the distribution of the sample means will tend to be
normal.</p>
<p>P-values less than 0.05 will be considered as statistically
significant.</p>
<div
id="took-prescription-medication-andor-received-counseling-or-therapy-for-mental-health"
class="section level3">
<h3>Took prescription medication and/or received counseling or therapy
for mental health</h3>
<p>The first independent samples t-test shows statistically significant
differences in prescription medication and/or counseling or therapy for
mental health rates. Men and women had statistically different mean
rates of taking prescription medication for mental health and/or
receiving counseling or therapy from 2020 to 2022 in the United
States.</p>
<pre class="r"><code>gender_received =
  tidydata |&gt;
  filter(
    indicator == &quot;Took Prescription Medication for Mental Health And/Or Received Counseling or Therapy&quot;,
    state == &quot;United States&quot;,
    group == &quot;Sex&quot;,
    subgroup %in% c(&quot;Male&quot;, &quot;Female&quot;)
  ) |&gt;
 dplyr::select(week_number, value, subgroup) |&gt;
  pivot_wider(
    names_from = &quot;subgroup&quot;,
    values_from = &quot;value&quot;) |&gt;
  janitor::clean_names()

gender_received |&gt;
  summarise(
    t_statistic = t.test(male, female)$statistic,
    p_value = t.test(male, female)$p.value) |&gt;
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">t_statistic</th>
<th align="right">p_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-39.52768</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
</div>
<div id="needed-counseling-or-therapy-but-did-not-get-it"
class="section level3">
<h3>Needed counseling or therapy but did not get it</h3>
<p>The second independent samples t-test shows statistically significant
differences in rates of needing counseling or therapy for mental health
but not getting it. Men and women had statistically different mean rates
of needing counseling or therapy for mental health but not getting it
from 2020 to 2022 in the United States.</p>
<pre class="r"><code>gender_needed =
  tidydata |&gt;
  filter(
    indicator == &quot;Needed Counseling or Therapy But Did Not Get It&quot;,
    state == &quot;United States&quot;,
    group == &quot;Sex&quot;,
    subgroup %in% c(&quot;Male&quot;, &quot;Female&quot;)
  ) |&gt;
  dplyr::select(week_number, value, subgroup) |&gt;
  pivot_wider(
    names_from = &quot;subgroup&quot;,
    values_from = &quot;value&quot;) |&gt;
  janitor::clean_names()

gender_needed |&gt;
  summarise(
    t_statistic = t.test(male, female)$statistic,
    p_value = t.test(male, female)$p.value) |&gt;
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">t_statistic</th>
<th align="right">p_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-24.12529</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="anova-sexual-orientation" class="section level2">
<h2>ANOVA: sexual orientation</h2>
<pre class="r"><code>sexuality_received =
  tidydata |&gt;
  filter(
    indicator == &quot;Took Prescription Medication for Mental Health And/Or Received Counseling or Therapy&quot;,
    state == &quot;United States&quot;,
    group == &quot;Sexual orientation&quot;,
    week_number %in% c(24:33)) |&gt;
  dplyr::select(week_number, value, subgroup) |&gt;
  pivot_wider(
    names_from = &quot;subgroup&quot;,
    values_from = &quot;value&quot;) |&gt;
  janitor::clean_names()</code></pre>
<pre class="r"><code>sexuality_needed =
  tidydata |&gt;
  filter(
    indicator == &quot;Needed Counseling or Therapy But Did Not Get It&quot;,
    state == &quot;United States&quot;,
    group == &quot;Sexual orientation&quot;,
    week_number %in% c(24:33)) |&gt;
  group_by(subgroup)</code></pre>
<div id="check-normality" class="section level3">
<h3>Check normality</h3>
<pre class="r"><code>ggplot(tidydata, aes(sample = value)) +
  stat_qq() +
  stat_qq_line()</code></pre>
<p><img src="statistical_analysis_files/figure-html/unnamed-chunk-6-1.png" width="90%" /></p>
<pre class="r"><code> hist(tidydata$value, breaks = &quot;FD&quot;, main = &quot;Histogram of Data&quot;, xlab = &quot;Data Values&quot;)</code></pre>
<p><img src="statistical_analysis_files/figure-html/unnamed-chunk-6-2.png" width="90%" />
The plot appears to be a Q-Q (quantile-quantile) plot showing that the
data deviates from the expected normal distribution, particularly in the
tails, indicating the presence of outliers or a heavy-tailed
distribution.</p>
<p>The histogram illustrates a bimodal frequency distribution of data
values, with significant concentrations of observations around two
central peaks, suggesting the presence of two subpopulations within the
dataset. The data range from near 0 to just over 60, with the majority
of values clustered between 5 and 30, and a notable right skew
indicating a tail of higher values extending towards 60. This skewness
and the thinning bars towards the right may also point to the existence
of outliers or extreme values in the dataset. The bimodal nature and the
distribution’s spread underscore the potential complexity within the
data, hinting at varied underlying characteristics or groups.</p>
<pre class="r"><code>ggplot(tidydata, aes(sample = log(value))) +
  stat_qq() +
  stat_qq_line()</code></pre>
<p><img src="statistical_analysis_files/figure-html/unnamed-chunk-7-1.png" width="90%" /></p>
<pre class="r"><code> hist(log(tidydata$value), breaks = &quot;FD&quot;, main = &quot;Histogram of Data&quot;, xlab = &quot;Data Values&quot;)</code></pre>
<p><img src="statistical_analysis_files/figure-html/unnamed-chunk-7-2.png" width="90%" />
Despite the application of a logarithmic transformation to the data, the
resulting distribution does not conform to normality. This is evidenced
by the Q-Q plot, which exhibits significant deviations from the line of
normality, particularly in the tails. Such persistent non-normality
suggests that the underlying data may not be log-normally distributed,
or there may be influential outliers that resist transformation.
Alternative transformations or non-parametric methods may be required to
address these distributional issues.</p>
<pre class="r"><code>tidydata=tidydata |&gt; mutate(subgroup=as.factor(subgroup),group=as.factor(group))
summary(pull(tidydata, value))</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.40   10.30   16.20   17.45   24.00   62.90</code></pre>
<p>The summary statistics for the value dataset indicate a right-skewed
distribution: the minimum value is 1.40, the first quartile is 10.30,
the median is 16.20, and the third quartile is 24.00, with a
considerably higher maximum value of 62.90. The mean, or average, is
17.45, which is higher than the median, further suggesting a
distribution with a right tail. The broad range from the minimum to the
maximum value points to a wide variation in the data, and the
displacement of the mean towards the higher end of the range hints at
the presence of outliers or a long tail to the right of the median.</p>
</div>
<div id="kruskal-wallis-test" class="section level3">
<h3>Kruskal-Wallis test</h3>
<pre class="r"><code>kruskal_result=kruskal.test(value ~ subgroup, data = tidydata)</code></pre>
<p>Kruskal-Wallis Chi-squared=1680.6. This is the test statistic that
follows a chi-squared distribution under the null hypothesis. A value of
1680.6 is quite large, suggesting a significant difference.</p>
<p>The p-value is less than 2.2e-16. It effectively means that the
p-value is extremely small, much less than the commonly used
significance levels (like 0.05 or 0.01), indicating that there is a
statistically significant difference in the medians across the
groups.</p>
<p>In summary, the test result is highly significant, which leads to the
rejection of the null hypothesis of equal medians. Therefore, we have
sufficient evidence to say that not all group medians are equal.</p>
</div>
</div>
<div id="continue-data-explorartion" class="section level2">
<h2>Continue Data Explorartion:</h2>
<p>Now we are going to break down the dataset into four subgroups based
the Indicator’s categories. We are going to explore the distribution of
each subgroup and perform the the most appropriate test.</p>
<pre class="r"><code>Indicator1=tidydata |&gt; filter(indicator==&quot;Took Prescription Medication for Mental Health&quot;)
Indicator2=tidydata |&gt; filter(indicator==&quot;Received Counseling or Therapy&quot;)
Indicator3=tidydata |&gt; filter(indicator==&quot;Took Prescription Medication for Mental Health And/Or Received Counseling or Therapy&quot;)
Indicator4=tidydata |&gt; filter(indicator==&quot;Needed Counseling or Therapy But Did Not Get It&quot;)</code></pre>
<ul>
<li>Step 1: Check Normality for Group of people who Took Prescription
Medication for Mental Health.</li>
</ul>
<pre class="r"><code>shapiro_test_result &lt;- shapiro.test(pull(Indicator1,value))

hist(Indicator1$value, breaks = &quot;FD&quot;, main = &quot;Histogram of Data&quot;, xlab = &quot;Data Values&quot;)</code></pre>
<p><img src="statistical_analysis_files/figure-html/unnamed-chunk-11-1.png" width="90%" />
Shapiro-Wilk normality test result : (W = 0.93709, p-value &lt;
2.2e-16), The p-value is extremely small (&lt; 2.2e-16), which provides
strong evidence suggest that the data does not come from a normal
distribution, and hence, we reject the null hypothesis of normality at
0.05 level of significance.</p>
<ul>
<li>Step2: Perform Kruskal-Wallis test for indicator 1 dataset</li>
</ul>
<pre class="r"><code>kruskal_result=kruskal.test(value ~ subgroup, data = Indicator1)</code></pre>
<p>Kruskal-Wallis Chi-squared=1812.7. This is the test statistic that
follows a chi-squared distribution under the null hypothesis. A value of
1812.7 is quite large, suggesting a significant difference.</p>
<p>The p-value is less than 2.2e-16. It effectively means that the
p-value is extremely small, much less than the commonly used
significance levels (like 0.05 or 0.01), indicating that there is a
statistically significant difference in the medians across the
groups.</p>
<p>In summary, the test result is highly significant, which leads to the
rejection of the null hypothesis of equal medians. Therefore, we have
sufficient evidence to say that not all group medians are equal.</p>
<ul>
<li>Step 3: Check normality for Group of people who Received Counseling
or Therapy</li>
</ul>
<pre class="r"><code>shapiro_test_result &lt;- shapiro.test(pull(Indicator2,value))

hist(Indicator2$value, breaks = &quot;FD&quot;, main = &quot;Histogram of Data&quot;, xlab = &quot;Data Values&quot;)</code></pre>
<p><img src="statistical_analysis_files/figure-html/unnamed-chunk-13-1.png" width="90%" />
Shapiro-Wilk normality test result : (W = 0.83846, p-value &lt;
2.2e-16), The p-value is extremely small (&lt; 2.2e-16), which provides
strong evidence suggest that the data does not come from a normal
distribution, and hence, we reject the null hypothesis of normality at
0.05 level of significance.</p>
<ul>
<li>step 4: Perform Kruskal-Wallis test for indicator 2 dataset</li>
</ul>
<pre class="r"><code>kruskal_result=kruskal.test(value ~ subgroup, data = Indicator2)</code></pre>
<p>Kruskal-Wallis Chi-squared=1784.5. This is the test statistic that
follows a chi-squared distribution under the null hypothesis. A value of
1784.5 is quite large, suggesting a significant difference.</p>
<p>The p-value is less than 2.2e-16. It effectively means that the
p-value is extremely small, much less than the commonly used
significance levels (like 0.05 or 0.01), indicating that there is a
statistically significant difference in the medians across the
groups.</p>
<p>In summary, the test result is highly significant, which leads to the
rejection of the null hypothesis of equal medians. Therefore, we have
sufficient evidence to say that not all group medians are equal.</p>
<ul>
<li>Step 5: Check normality for Group of people who Took Prescription
Medication for Mental Health And/Or Received Counseling or Therapy</li>
</ul>
<pre class="r"><code>shapiro_test_result &lt;- shapiro.test(pull(Indicator3,value))

hist(Indicator3$value, breaks = &quot;FD&quot;, main = &quot;Histogram of Data&quot;, xlab = &quot;Data Values&quot;)</code></pre>
<p><img src="statistical_analysis_files/figure-html/unnamed-chunk-15-1.png" width="90%" />
Shapiro-Wilk normality test result : (W = 0.95871, p-value &lt;
2.2e-16), The p-value is extremely small (&lt; 2.2e-16), which provides
strong evidence suggest that the data does not come from a normal
distribution, and hence, we reject the null hypothesis of normality at
0.05 level of significance.</p>
<ul>
<li>step 6: Perform Kruskal-Wallis test for Indicator 3 dataset</li>
</ul>
<pre class="r"><code>kruskal_result=kruskal.test(value ~ subgroup, data = Indicator3)</code></pre>
<p>Kruskal-Wallis Chi-squared=1750.7. This is the test statistic that
follows a chi-squared distribution under the null hypothesis. A value of
1750.7 is quite large, suggesting a significant difference.</p>
<p>The p-value is less than 2.2e-16. It effectively means that the
p-value is extremely small, much less than the commonly used
significance levels (like 0.05 or 0.01), indicating that there is a
statistically significant difference in the medians across the
groups.</p>
<p>In summary, the test result is highly significant, which leads to the
rejection of the null hypothesis of equal medians. Therefore, we have
sufficient evidence to say that not all group medians are equal.</p>
<ul>
<li>Step 7: Check normality for Group of people who Needed Counseling or
Therapy But Did Not Get It.</li>
</ul>
<pre class="r"><code>shapiro_test_result &lt;- shapiro.test(pull(Indicator4,value))

hist(Indicator4$value, breaks = &quot;FD&quot;, main = &quot;Histogram of Data&quot;, xlab = &quot;Data Values&quot;)</code></pre>
<p><img src="statistical_analysis_files/figure-html/unnamed-chunk-17-1.png" width="90%" />
Shapiro-Wilk normality test result : (W = 0.8161, p-value &lt; 2.2e-16),
The p-value is extremely small (&lt; 2.2e-16), which provides strong
evidence suggest that the data does not come from a normal distribution,
and hence, we reject the null hypothesis of normality at 0.05 level of
significance.</p>
<ul>
<li>step 8: Perform Kruskal-Wallis test for Indicator 4 dataset</li>
</ul>
<pre class="r"><code>kruskal_result=kruskal.test(value ~ subgroup, data = Indicator4)</code></pre>
<p>Kruskal-Wallis Chi-squared=1539.6. This is the test statistic that
follows a chi-squared distribution under the null hypothesis. A value of
1539.6 is quite large, suggesting a significant difference.</p>
<p>The p-value is less than 2.2e-16. It effectively means that the
p-value is extremely small, much less than the commonly used
significance levels (like 0.05 or 0.01), indicating that there is a
statistically significant difference in the medians across the
groups.</p>
<p>In summary, the test result is highly significant, which leads to the
rejection of the null hypothesis of equal medians. Therefore, we have
sufficient evidence to say that not all group medians are equal.</p>
</div>
<div id="linear-modeling" class="section level2">
<h2>Linear Modeling</h2>
<div id="step-1" class="section level3">
<h3>Step 1</h3>
<p>Import the tidy dataset</p>
<pre class="r"><code>library(tidyverse)

tidydata = 
  read.csv(&quot;data/tidydata.csv&quot;)</code></pre>
</div>
<div id="step-2" class="section level3">
<h3>Step 2</h3>
<p>Separate tidy dataset into 4 subgroups based on the indicator
category.</p>
<pre class="r"><code>Indicator1=tidydata |&gt; filter(indicator==&quot;Took Prescription Medication for Mental Health&quot;)
Indicator2=tidydata |&gt; filter(indicator==&quot;Received Counseling or Therapy&quot;)
Indicator3=tidydata |&gt; filter(indicator==&quot;Took Prescription Medication for Mental Health And/Or Received Counseling or Therapy&quot;)
Indicator4=tidydata |&gt; filter(indicator==&quot;Needed Counseling or Therapy But Did Not Get It&quot;)</code></pre>
</div>
<div id="step-3" class="section level3">
<h3>Step 3</h3>
<p>Apply linear model</p>
<pre class="r"><code>fit &lt;- lm(value ~ group + subgroup + year + state, data=Indicator1)
stepwise_fit &lt;- stepAIC(fit, direction=&quot;both&quot;)</code></pre>
<pre><code>## Start:  AIC=3614.67
## value ~ group + subgroup + year + state
## 
## 
## Step:  AIC=3614.67
## value ~ group + subgroup + year
## 
## 
## Step:  AIC=3614.67
## value ~ subgroup + year
## 
##            Df Sum of Sq   RSS    AIC
## &lt;none&gt;                   9973 3614.7
## - year      1      1300 11273 3917.1
## - subgroup 79     54300 64273 8085.1</code></pre>
<pre class="r"><code>fit &lt;- lm(value ~ group + subgroup + year + state, data=Indicator2)
stepwise_fit &lt;- stepAIC(fit, direction=&quot;both&quot;)</code></pre>
<pre><code>## Start:  AIC=1848.9
## value ~ group + subgroup + year + state
## 
## 
## Step:  AIC=1848.9
## value ~ group + subgroup + year
## 
## 
## Step:  AIC=1848.9
## value ~ subgroup + year
## 
##            Df Sum of Sq   RSS    AIC
## &lt;none&gt;                   4894 1848.9
## - year      1     635.1  5529 2149.0
## - subgroup 79   30155.9 35050 6565.7</code></pre>
<pre class="r"><code>fit &lt;- lm(value ~ group + subgroup + year + state, data=Indicator3)
stepwise_fit &lt;- stepAIC(fit, direction=&quot;both&quot;)</code></pre>
<pre><code>## Start:  AIC=3879.24
## value ~ group + subgroup + year + state
## 
## 
## Step:  AIC=3879.24
## value ~ group + subgroup + year
## 
## 
## Step:  AIC=3879.24
## value ~ subgroup + year
## 
##            Df Sum of Sq   RSS    AIC
## &lt;none&gt;                  11093 3879.2
## - year      1      1773 12866 4245.5
## - subgroup 79     64454 75547 8486.6</code></pre>
<pre class="r"><code>fit &lt;- lm(value ~ group + subgroup + year + state, data=Indicator4)
stepwise_fit &lt;- stepAIC(fit, direction=&quot;both&quot;)</code></pre>
<pre><code>## Start:  AIC=2722.17
## value ~ group + subgroup + year + state
## 
## 
## Step:  AIC=2722.17
## value ~ group + subgroup + year
## 
## 
## Step:  AIC=2722.17
## value ~ subgroup + year
## 
##            Df Sum of Sq   RSS    AIC
## &lt;none&gt;                   6964 2722.2
## - year      1       141  7105 2769.7
## - subgroup 79     40494 47457 7304.4</code></pre>
</div>
<div id="step-4" class="section level3">
<h3>Step 4</h3>
<p>AIC values are identical across the steps shown, which suggests that
removal or addition of a variable did not improve the model’s fit.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
